// This file is automatically generated. Do not edit it directly.
// Powered by EnterCloud Managed Supabase
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://spb-t4ngq0ib2t3myygs.supabase.opentrust.net";
export const SUPABASE_PUBLISHABLE_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiYW5vbiIsInJlZiI6InNwYi10NG5ncTBpYjJ0M215eWdzIiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE3ODk2MzgyNjYsImV4cCI6MjEwNTIxNDI2Nn0.gpTAzMJlKkzS0NI7s4_RxxcC-JkCXSAHfdZg1Nc47LA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
